<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_node().
 */
function lms_progress_preprocess_node(&$variables) {
  $node = $variables['node'];

  if ($node->bundle() === 'leccion') {
    $user = Drupal::currentUser();
    $service = Drupal::service('lms_progress.progress_service');

    $completed = $service->isLessonCompleted(
      $user->id(),
      $node->id()
    );

    $variables['lesson_completed'] = $completed;
    # Desactiva el cache para que el progreso se actualice en tiempo real
    $variables['#cache']['max-age'] = 0;

  }
}
